{% set version = "2.9.6621" %}

package:
  name: miktex
  version: {{ version }}

source:
  fn: miktex-portable-{{ version }}.exe
  url: http://mirrors.ctan.org/systems/win32/miktex/setup/windows-x86/miktex-portable-{{ version }}.exe
  sha256: cc5a8ef0822378c72a3b95fa43852c740ba8c3b07b440e963db0e73f25a4f213

build:
  skip: True  # [not win]
  skip: True  # [win and vc!=14]
  number: 1000
  binary_relocation: false
  ignore_run_exports:
    - vc

requirements:
  build:
    - 7za
    - {{ compiler("c") }}
  run:
    - vs2015_runtime

test:
  commands:
    - pdflatex.exe --help
    - mpm --help
    - initexmf.exe --report
    # this is from the problem in matplotlib: it needs to find that font file
    - kpsewhich cmss10.tfm | findstr cmss10

about:
  home: http://miktex.org/
  license: various, see http://miktex.org/copying
  summary: Implementation of TeX/LaTeX for Windows (repackaged binaries)

extra:
  recipe-maintainers:
    - ivoflipse
    - Korijn
    - jankatins
