travis:
  secure:
    BINSTAR_TOKEN: geQl1TjJFVeA1aLcGDBJOth8kTLUSfHeED79WZRW0Pjkc/lRmYsZWAhF9WLhyzCcMKswk0jnZuSk7cFfmsj3jXhLgYWKlktWX4Ofxiw5aAzGjq3SpmpQz1VmukLIz8ISO3e5ZmacQ0/g5TQt0R9dKoSqvSE1g26oPt6NAX/1HR15e7VCOGkWV0qY3EkJoaYVUvdhXB+x2IvdgrCde8ZnlqR1GvyRt3bdqcrdMjSRTHz6/oDXOjzw3Wbd8deD4JTDuWAP5lWuifQtk/aI8zfJGXcX4h7xKWREGrheqlJrMAi1fThul7FN6Qqn+JYfhywUu8CBI4eSVZO3JF0cpqbu2+26vmAucNrV46/tvMqJX1sfRfXUqg6Xx3hPw64g1VB+XofzMNSvsNoK5VeC3UC5jDRo9e4UoHFksvtD6b0uZIdf40mnITHl16xlgb8yu23mvZyxPgRub5iCqlpF+uPAPuVNSw4WIWl3dv4nRWy1zbgc1+L4v0QUuES6m9M30t36lWbJzHry7rDtdU6iT2s0ZeO/02KGeKri0F26pDcUOb8W6AMZqmpHdR19jzFGI9zGYpbK5V8605G5JTA9Hc95v4bM9Q57S3Kh7pUqfAKghcC7eW5e3wnorx9TGHNr2aX4Gp0mTwVTletehdar3E2DKQeZsSb5p+6qd6kWBr4NACs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
